/*
    Copyright 1996-2008 Ariba, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    $Id:$
*/

package ariba.ideplugin.idea.lang.grammer;

import com.intellij.lexer.FlexAdapter;
import com.intellij.lexer.LookAheadLexer;


/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/1/13 12:12 PM from the specification file
 * <tt>/ariba/opensourceui/ariba/platform/ui/ideplugin12/ariba/ideplugin/idea/lang
 * /grammer/OSS
 * .flex</tt>
 */
public class OSSLexer extends LookAheadLexer
{
    public OSSLexer ()
    {
        super(new FlexAdapter(new _OSSLexer()));
    }
}