/*
    Copyright 1996-2008 Ariba, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    $Id: //ariba/platform/util/core/ariba/util/formatter/DecimalParseInfo.java#4 $
*/

package ariba.util.formatter;

import java.math.BigDecimal;

/**
    This class contains information generated by parsing a given
    BigDecimal string.

    @aribaapi documented
*/
public class DecimalParseInfo
{
    /**
        The number of digits before the decimal separator
        @aribaapi documented
    */
    public int integerDigits;

    /**
        The number of digits after the decimal separator
        @aribaapi documented
    */
    public int decimalDigits;

    /**
        The parse location of the decimal separator (in characters)
        @aribaapi documented
    */
    public int decimalLocation;

    /**
        The string prefix of the number
        @aribaapi documented
    */
    public String prefix;

    /**
        The string suffix of the number
        @aribaapi documented
    */
    public String suffix;

    /**
        The number parsed
        @aribaapi documented
    */
    public BigDecimal number;

    /**
        Constructor for initializing the public fields on this
        class.  It is of package visibility since this class should
        only be created by the MoneyFormatter.
        @aribaapi documented
    */
    DecimalParseInfo (int        integerDigits,
                      int        decimalDigits,
                      int        decimalLocation,
                      String     prefix,
                      String     suffix,
                      BigDecimal number)
    {
        this.integerDigits   = integerDigits;
        this.decimalDigits   = decimalDigits;
        this.decimalLocation = decimalLocation;
        this.prefix          = prefix;
        this.suffix          = suffix;
        this.number          = number;
    }
}
