/*
    Copyright (c) 2013-2013 Ariba, Inc.
    All rights reserved. Patents pending.

    $Id: //ariba/platform/util/core/ariba/util/core/MimeEncoding.java#2 $

    Responsible: hprabhakara
*/
package ariba.util.core;

import java.util.Set;
import java.util.HashSet;
/**
 * This class is generated by Add Language Tool.
 * Pls don't edit this directly
 */
public abstract class MimeEncoding
{
    protected static final Set<String> EncodingSet = new HashSet<String>();

    public static final String CharSetISO88591        = "ISO-8859-1";
    public static final String CharSetISO88592        = "ISO-8859-2";
    public static final String CharSetISO88598        = "ISO-8859-8";
    public static final String CharSetISO2022CN        = "ISO-2022-CN";
    public static final String CharSetISO2022JP        = "ISO-2022-JP";
    public static final String CharSetISO2022KR        = "ISO-2022-KR";
    public static final String CharSetBig5        = "Big5";
    public static final String CharSetGB2312        = "GB2312";
    public static final String CharSetKSC5601        = "KSC5601";
    public static final String CharSetUTF        = "UTF-8";
    public static final String CharSetShiftJIS        = "Shift_JIS";
    public static final String CharSetEUCKR        = "EUC-KR";
    public static final String CharSetEUCJP        = "EUC-JP";
    public static final String CharSetCp1252        = "Cp1252";
    public static final String CharSetCp1251        = "Cp1251";
    public static final String CharSetCp1254        = "Cp1254";
    public static final String CharSetCp1250        = "Cp1250";
    public static final String CharSetCp1253        = "Cp1253";

    public MimeEncoding ()
    {
       EncodingSet.add(CharSetISO88591.toLowerCase());
       EncodingSet.add(CharSetISO88592.toLowerCase());
       EncodingSet.add(CharSetISO88598.toLowerCase());
       EncodingSet.add(CharSetISO2022CN.toLowerCase());
       EncodingSet.add(CharSetISO2022JP.toLowerCase());
       EncodingSet.add(CharSetISO2022KR.toLowerCase());
       EncodingSet.add(CharSetBig5.toLowerCase());
       EncodingSet.add(CharSetGB2312.toLowerCase());
       EncodingSet.add(CharSetKSC5601.toLowerCase());
       EncodingSet.add(CharSetUTF.toLowerCase());
       EncodingSet.add(CharSetShiftJIS.toLowerCase());
       EncodingSet.add(CharSetEUCKR.toLowerCase());
       EncodingSet.add(CharSetEUCJP.toLowerCase());
       EncodingSet.add(CharSetCp1252.toLowerCase());
       EncodingSet.add(CharSetCp1251.toLowerCase());
       EncodingSet.add(CharSetCp1254.toLowerCase());
       EncodingSet.add(CharSetCp1250.toLowerCase());
       EncodingSet.add(CharSetCp1253.toLowerCase());

    }
}
